sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 112233new

  alioss:
    endpoint:
    bucketName: java-shan
    region: cn-beijing
    accessKeyId: ${ALICLOUD_ACCESS_KEY_ID}
    accessKeySecret: ${ALICLOUD_ACCESS_KEY_SECRET}

  redis:
    host: localhost
    port: 6379
    database: 0

  wechat:
    appid:
    secret:
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl:
